### ISSUE TITLE
Installation instruction for composer needs update

### ISSUE THREAD

**Issue by svenk** [stackphp/url-map#19]
The Readme in this repository says to run `$ php composer.phar require chh/url-map:~1.0@dev`. However, the upstream package moved to https://packagist.org/packages/stack/url-map and installing `stack/url-map` at the current version 1.1 with composer is as easy as running

```
$ composer require stack/url-map
```

This should be updated in the README.

**Comment by harikt** [comment]
This can be closed for the current read me has fixed this.
