### ISSUE TITLE
Stable release for Symfony v3? 

### ISSUE THREAD

**Issue by gsdevme** [stackphp/url-map#20]
Hey is it possible to make a release for Symfony 3 please? Thanks in advance. 

**Issue**
1.1.0 release requires `~2.1` in the composer, however the code has been done to allow Symfony v3 see https://github.com/stackphp/url-map/compare/v1.1.0...master

**Solution for now**

```
"stack/url-map": "dev-master#7788a63a3a1d293b1fc7c46f0208c9a7ed8a7835 as 1.2.0"
```

**Comment by fadoe** [comment]
Is this project still maintained? @CHH

**Comment by fabpot** [comment]
Done
